### ISSUE TITLE
Multi-Monitor issue

### ISSUE THREAD

**Issue by RandomLegend** [fluoroom/fluoroom-gnome-top-bar#2]
I use two monitors and use the multi-monitor extension to get the top bar on both screens.

Your extension gives me the black topbar with rounded edges on my 2nd screen but the round backdrop when you hover over a a topbar icon is on my mainscreen (because all my icons are on the main screen).

I would love to have the black top bar with rounded edges to all my windows my main screen aswell.

Any idea how to fix that?

![grafik](https://user-images.githubusercontent.com/38812603/139508935-73bd464f-fc3f-4c44-8338-43a2decdefe4.png)

**Comment by fluoroom** [comment]
Hi! Sorry i just read it now! Unfortunately i'm no longer working with Gnome at the moment nor have i access to an emulator to continue developing and testing. I'd really like to solve this and i'll try, but i cannot ensure anything by now.
Sharing the proyect could have someone solving it and ideally making a pull request.
Thanks for letting me know!

**Comment by RandomLegend** [comment]
Hey, im also sorry! i already "fixed" it and forgot to close this issue. My bad!

It was some interference with another extension. Also i switched to arch at this point so i dont mind at all.

Dont worry, and i hope you are fine. Stay safe
